export const RPC_ALERT_BUTTON_TEXT = 'Switch to Uni.live RPC'
export const RPC_ALERT_TRANSPARENT_BUTTON_TEXT = 'Let me look first'
export const RPC_ALERT_ICON_COLOR = '#5C67F7'
export const DEFAULT_RPC_URL = 'default_RPC_URL'
export const UNI_LIVE_DOC_LINK = 'https://docs.bloxroute.com/introduction/uni.live'
